import fs from 'node:fs'; import path from 'node:path'; import { unified } from 'unified'; import remarkParse from 'remark-parse';
import { makePageId, makeThemeId } from './ids'; import { reportMissingAliases, slugFor } from './slug-map'; import type { Community, ThemeType } from '@/types/community';
const file = path.join(process.cwd(), 'docs', 'Community-topics.md');
const headingText = (node: any) => node.children.map((c: any) => c.value ?? '').join('').trim();
export function loadCommunities(): Community[] {
 const tree: any = unified().use(remarkParse).parse(fs.readFileSync(file, 'utf8')); const result: Community[] = []; const routes = new Map<string,string[]>(); let trail: string[] = []; let current: { path: string[]; sections: Partial<Record<ThemeType,string[]>> } | undefined; let section: ThemeType | undefined;
 const finish = () => { if (!current) return; const { kami5, naka7 } = current.sections; if (!kami5?.length || !naka7?.length) throw new Error(`テーマリストが不足: ${current.path.join(' ＞ ')}`); const rawSlugs=current.path.map((name,index)=>slugFor(name,index===0?'categories':index===1?'subcategories':'communities')); const slugs=rawSlugs.filter((s,i)=>i===0||s!==rawSlugs[i-1]); const route=slugs.join('/'); const existing=routes.get(route); if(existing){const fallback=Array.from(current.path.join('/')).map(c=>c.codePointAt(0)!.toString(36)).join('-'); console.warn(`⚠ URL slug 重複: 「${existing.at(-1)}」と「${current.path.at(-1)}」が ${route} を生成しました。暫定IDを使用します。`); slugs[slugs.length-1]=`${slugs.at(-1)}--${fallback}`;} routes.set(slugs.join('/'),current.path); const id=makePageId(slugs); result.push({ id, path:current.path, slugs, name:current.path.at(-1)!, kami5:kami5.map(text=>({id:makeThemeId(id,'kami5',text),text,type:'kami5'})), naka7:naka7.map(text=>({id:makeThemeId(id,'naka7',text),text,type:'naka7'})) }); current=undefined; section=undefined;
 };
 for (const node of tree.children) { if (node.type==='heading' && node.depth<=4) { const text=headingText(node); if(node.depth===4){ if(!trail.length) throw new Error(`上位見出しがありません: ${text}`); if(!current) current={path:[...trail],sections:{}}; if(text==='上五') section='kami5'; else if(text==='中七') section='naka7'; else throw new Error(`不正な####見出し: ${text}`); continue; } finish(); if(node.depth>trail.length+1) throw new Error(`見出し階層が壊れています: ${text}`); trail=trail.slice(0,node.depth-1); trail[node.depth-1]=text; section=undefined; continue; } if(node.type==='list' && section){ const values=node.children.filter((i:any)=>i.type==='listItem').map((i:any)=>i.children.map((p:any)=>p.children?.map((t:any)=>t.value??'').join('')??'').join('').trim()).filter(Boolean); if(values.length) { if(!current) current={path:[...trail],sections:{}}; current.sections[section]=[...(current.sections[section]??[]),...values]; } } }
 finish(); reportMissingAliases(); return result;
}
